### ISSUE TITLE
Cannot run unity app

### ISSUE THREAD

**Issue by lochoang75** [fpt-corp/ROS_Package_example#4]
I try to run newest app, which was updated at (4/11/2018),  but some log appear 
./test.x86_64: line 1: version: command not found
./test.x86_64: line 2: oid: command not found
size: '100719740': No such file

**Comment by miamor** [comment]
I got the same error too. And when I run file test.x86_64, it gives ASCII text, which clearly not an executable file.

**Comment by ducvietmta** [comment]
git large file dang loi, minh se gui lai link driver sau nhe

**Comment by kuroemon2509** [comment]
It is stored in git lfs (large file storage). You can get it by using the following command:
`git lfs pull --include "<file_name>"` to pull a single file or `git lfs pull` to pull all the files being stored in lfs.
